# This file is generated by Nx.
#
# Build the docker image with `npx nx docker-build fastify-docs-nx`.
# Tip: Modify "docker-build" options in project.json to change docker build args.
#
# Run the container with `docker run -p 3000:3000 -t fastify-docs-nx`.
FROM docker.io/node:lts-alpine

ENV HOST=0.0.0.0
ENV PORT=3000

WORKDIR /app

RUN addgroup --system fastify-docs-nx && \
          adduser --system -G fastify-docs-nx fastify-docs-nx

COPY dist/fastify-docs-nx fastify-docs-nx
RUN chown -R fastify-docs-nx:fastify-docs-nx .

# You can remove this install step if you build with `--bundle` option.
# The bundled output will include external dependencies.
RUN npm --prefix fastify-docs-nx --omit=dev -f install

CMD [ "node", "fastify-docs-nx" ]
